/* 
 * Copyright 2014 OpenMarket Ltd
 * Copyright 2017 OpenMarket Ltd
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.matrix.androidsdk.rest.api;

import org.matrix.androidsdk.rest.model.BulkLookupParams;
import org.matrix.androidsdk.rest.model.BulkLookupResponse;
import org.matrix.androidsdk.rest.model.PidResponse;
import org.matrix.androidsdk.rest.model.RequestEmailValidationResponse;
import org.matrix.androidsdk.rest.model.RequestPhoneNumberValidationResponse;

import java.util.Map;

import retrofit.Callback;
import retrofit.http.Body;
import retrofit.http.GET;
import retrofit.http.POST;
import retrofit.http.Path;
import retrofit.http.Query;

public interface ThirdPidApi {

    /**
     * Get the 3rd party id from a medium
     *
     * @param address  the address.
     * @param medium   the medium.
     * @param callback the asynchronous callback called with the response
     */
    @GET("/lookup")
    void lookup3Pid(@Query("address") String address,
                    @Query("medium") String medium, Callback<PidResponse> callback);

    /**
     * Request a bunch of 3PIDs
     *
     * @param body     teh body request
     * @param callback the asynchronous callback.
     */
    @POST("/bulk_lookup")
    void bulkLookup(@Body BulkLookupParams body, Callback<BulkLookupResponse> callback);

    /**
     * Request an email validation
     *
     * @param clientSecret the client secret
     * @param email        the email address
     * @param sendAttempt  the attempt count
     * @param nextLink     the next link
     * @param callback     the asynchronous callback called with the response
     */
    @POST("/validate/email/requestToken")
    void requestEmailValidation(@Query("client_secret") String clientSecret,
                                @Query("email") String email,
                                @Query("send_attempt") Integer sendAttempt,
                                @Query("next_link") String nextLink, Callback<RequestEmailValidationResponse> callback);

    /**
     * Request a phone number validation
     *
     * @param clientSecret the client secret
     * @param phoneNumber  the phone number
     * @param country      the country
     * @param sendAttempt  the attempt count
     * @param nextLink     the next link
     * @param callback     the asynchronous callback called with the response
     */
    @POST("/validate/msisdn/requestToken")
    void requestPhoneNumberValidation(@Query("client_secret") String clientSecret,
                                      @Query("phone_number") String phoneNumber,
                                      @Query("country") String country,
                                      @Query("send_attempt") Integer sendAttempt,
                                      @Query("next_link") String nextLink,
                                      Callback<RequestPhoneNumberValidationResponse> callback);

    /**
     * Request the ownership validation of an email address or a phone number previously set
     * by {@link #requestEmailValidation(String, String, Integer, String, Callback)}.
     *
     * @param medium       the medium of the 3pid
     * @param token        the token generated by the requestToken call
     * @param clientSecret the client secret which was supplied in the requestToken call
     * @param sid          the sid for the session
     * @param callback     asynchronous callback response
     */
    @POST("/validate/{medium}/submitToken")
    void requestOwnershipValidation(@Path("medium") String medium,
                                    @Query("token") String token,
                                    @Query("client_secret") String clientSecret,
                                    @Query("sid") String sid, Callback<Map<String, Object>> callback);
}
